# Generated by Django 4.2.6 on 2023-11-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Chat',
        ),
    ]
