# Generated by Django 4.2.6 on 2023-11-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_room_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
