# Generated by Django 4.2.6 on 2023-11-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_rename_room_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='group_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_chat',
            field=models.ManyToManyField(related_name='user_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
