# Generated by Django 4.2.6 on 2023-11-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
    ]
