# Generated by Django 4.2.6 on 2023-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_chat_name_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
